services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: on-failure
  backend:
    build:
      context: .
      dockerfile: dockers/backend.dockerfile
    ports:
      - "8000:8000"
    restart: on-failure 
    depends_on:
      - redis
